// Generated by scripts/build - do not edit manually.
const path = require("path");
const fs = require("fs");
const { spawnSync } = require("child_process");

// This file lives at the root of dist/opencode/; assets are its siblings.
const PLUGIN_ROOT = path.resolve(__dirname);
for (const asset of [__ASSET_LIST__]) {
  if (!fs.existsSync(path.join(PLUGIN_ROOT, asset))) {
    throw new Error("hercules opencode plugin: missing asset " + asset);
  }
}

// A bare `module.exports = <function>` breaks OpenCode's real (Bun-compiled) loader: Bun's
// CJS/ESM interop spreads a plain function's own `length`/`name` properties into the imported
// module's namespace object alongside the function itself, and the loader iterates every value
// in that namespace, throwing on the first one that isn't a valid plugin export. Exporting a
// plain object instead avoids this entirely, and matches OpenCode's own documented
// `PluginModule` shape (`{ id, server: Plugin }`) rather than relying on its bare-function
// fallback. `id` is required in practice for a path-installed plugin (the loader rejects a
// path plugin with "must export id" even though the type marks it optional).
// See https://github.com/mbienkowski/hercules/issues/15 for the full diagnosis.
// Hard write-gate (G1). Reuses the CANONICAL Python guard shipped at hooks/frozen_tests.py — the
// same code Claude Code runs as a PreToolUse hook — so all three ecosystems share one source of
// truth. `tool.execute.before` runs before the real Write/Edit executes; THROWING aborts it, a true
// pre-write veto matching Claude's exit-2 gate. Fails OPEN (allow) if python3 is absent, the guard
// file is missing, or anything errors — so it is a progressive enhancement that never bricks an edit.
// OpenCode tool ids map onto the Claude tool names the guard expects.
const WRITE_TOOLS = { edit: "Edit", write: "Write", apply_patch: "MultiEdit", patch: "MultiEdit" };
function makeWriteGate(projectDir) {
  const guard = path.join(PLUGIN_ROOT, "hooks", "frozen_tests.py");
  return (input, output) => {
    let reason = null;
    try {
      const claudeTool = WRITE_TOOLS[input && input.tool];
      if (!claudeTool) return;
      const args = (output && output.args) || {};
      const paths = [];
      const direct = args.filePath || args.file_path;
      if (direct) paths.push(direct);
      if (typeof args.patchText === "string") {
        // apply_patch is multi-file: EVERY "*** ... File: <path>" hunk header is a write target, so
        // check them all — a frozen file in a later hunk must still block (checking only the first
        // let an innocuous-first, frozen-second patch slip the veto).
        for (const line of args.patchText.split("\n")) {
          const idx = line.indexOf(" File: ");
          if (idx !== -1 && line.indexOf("*** ") === 0) paths.push(line.slice(idx + 7).trim());
        }
      }
      if (!paths.length || !fs.existsSync(guard)) return;
      for (const filePath of paths) {
        const payload = JSON.stringify({ tool_name: claudeTool, tool_input: { file_path: filePath }, cwd: projectDir });
        const r = spawnSync("python3", [guard], { input: payload, encoding: "utf8", timeout: 10000 });
        if (r && r.status === 2) { reason = (r.stderr || "").trim() || "edit to a frozen test file denied during build"; break; }
      }
    } catch (e) {
      return; // fail open: python3 missing / spawn error must never brick an unrelated edit
    }
    if (reason) throw new Error("hercules write-gate — " + reason);
  };
}

module.exports = {
  id: "hercules",
  server: async (input) => {
    const projectDir = (input && input.directory) || process.cwd();
    return {
      config: (cfg) => {
        cfg.default_agent = __DEFAULT_AGENT__;
        // Persona + protocols are always-loaded so their `§`/path references resolve
        // (OpenCode has no ${CLAUDE_PLUGIN_ROOT}; the plugin injects absolute paths here).
        cfg.instructions = [
          ...(cfg.instructions || []),
          __INSTRUCTION_JOINS__
        ];
        cfg.skills = cfg.skills || {};
        cfg.skills.paths = [
          ...(cfg.skills.paths || []),
          path.join(PLUGIN_ROOT, __SKILLS_PATH__),
        ];
        cfg.agent = { ...(cfg.agent || {}), ...__AGENT_ENTRIES__ };
        cfg.command = { ...(cfg.command || {}), ...__COMMAND_ENTRIES__ };
      },
      "tool.execute.before": makeWriteGate(projectDir),
    };
  },
};
